// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNiW5TD_4NTrcnDYmxwd6uYOg8kkp9drI',
    appId: '1:45693887163:web:d31125b97d56e4da14bf9e',
    messagingSenderId: '45693887163',
    projectId: 'todo-sample-fdf6b',
    authDomain: 'todo-sample-fdf6b.firebaseapp.com',
    storageBucket: 'todo-sample-fdf6b.appspot.com',
    measurementId: 'G-9WQYXGNHP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS6N2Szg4Y6G9sjNsaFvlxfz9KyzjAZQ4',
    appId: '1:45693887163:android:26793186d203bf0e14bf9e',
    messagingSenderId: '45693887163',
    projectId: 'todo-sample-fdf6b',
    storageBucket: 'todo-sample-fdf6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD633gcJ1qVuSwVAtUs866Lpjk8iMzjK1o',
    appId: '1:45693887163:ios:d456b489f42fb00f14bf9e',
    messagingSenderId: '45693887163',
    projectId: 'todo-sample-fdf6b',
    storageBucket: 'todo-sample-fdf6b.appspot.com',
    iosClientId: '45693887163-cvipt76ic1g054pvenkapb7su9h5gcpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAsyncNotifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD633gcJ1qVuSwVAtUs866Lpjk8iMzjK1o',
    appId: '1:45693887163:ios:d456b489f42fb00f14bf9e',
    messagingSenderId: '45693887163',
    projectId: 'todo-sample-fdf6b',
    storageBucket: 'todo-sample-fdf6b.appspot.com',
    iosClientId: '45693887163-cvipt76ic1g054pvenkapb7su9h5gcpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAsyncNotifier',
  );
}
